import { writable } from "svelte/store";

export const feedbackStore = writable([
    {name:"Palak" , email:"palak@gmail.com", feedback:"Your food service website is amazing, I love the menu options!"},
    {name:"Kevin" , email:"kevin@gmail.com", feedback:" Your website makes ordering food so convenient and easy!"},
    {name:"Bharti" , email:"bharti@gmail.com", feedback:"The food I ordered from your website was absolutely delicious!"},
    {name:"Parth" , email:"parth@gmail.com", feedback:"Your website has a great layout, making it easy to find what I want."},
    {name:"Kevin" , email:"kevin@gmail.com", feedback:"The online ordering process on your website is quick and seamless."},
    {name:"Bharti" , email:"bharti@gmail.com", feedback:"The food arrived on time and was still hot - great job!"},
    {name:"Vishruti" , email:"vishruti@gmail.com", feedback:"Your website is user-friendly and easy to navigate."},
    {name:"Mona" , email:"mona@gmail.com", feedback:"The variety of food options on your website is impressive."},
    {name:"Nilesh" , email:"nilesh@gmail.com", feedback:"The food quality exceeded my expectations, I will definitely order again."},
    {name:"Ram" , email:"ram@gmail.com", feedback:"Your website is a lifesaver when I don't feel like cooking!"},
    {name:"Shyam" , email:"shyam@gmail.com", feedback:"The food was packaged neatly and securely for delivery."},
    {name:"Janvi" , email:"Janvi@gmail.com", feedback:"Your website has made ordering food for my family so much easier."},
    {name:"Hardik" , email:"Hardik@gmail.com", feedback:"The online payment process on your website is secure and reliable."},
    {name:"Zalak" , email:"Zalak@gmail.com", feedback:"The delivery driver was friendly and professional - great service!"},
    {name:"Jitesh" , email:"Jitesh@gmail.com", feedback:"Your website has a great selection of vegetarian options."},
    {name:"Jayesh" , email:"Jayesh@gmail.com", feedback:"The food I ordered tasted fresh and flavorful."},
    {name:"Pratik" , email:"Pratik@gmail.com", feedback:"Your website has a great system for tracking my order's status."},
    {name:"Narendra" , email:"Narendra@gmail.com", feedback:"The food was packaged with care to ensure it arrived in great condition."},
    {name:"Kush" , email:"Kush@gmail.com", feedback:"Your website is a go-to for my office's lunch orders."},
    {name:"Keval" , email:"Keval@gmail.com", feedback:"The portions of food are generous and filling."},
    {name:"Ishan" , email:"Ishan@gmail.com", feedback:"Your website's search function makes it easy to find what I'm looking for."},
    {name:"Vihan" , email:"Vihan@gmail.com", feedback:"The food arrived earlier than expected - thank you for the prompt service!"},
    {name:"Ayushi" , email:"Ayushi@gmail.com", feedback:"Your website's prices are very reasonable for the quality of food."},
    {name:"Payal" , email:"payal@gmail.com", feedback:"The food arrived exactly as I had customized it on your website."},
    {name:"Sooraj" , email:"sooraj@gmail.com", feedback:"Your website has a great feature of saving my previous orders for easy reordering."},
    {name:"Aarav" , email:"Aarav@gmail.com", feedback:"Your website's search function makes it easy to find what I'm looking for."},
    {name:"Chirag" , email:"Chirag@gmail.com", feedback:"The food was packaged neatly and securely for delivery."},
    {name:"Darshan" , email:"darshan@gmail.com", feedback:"Your website is user-friendly and easy to navigate."}
]);