import { writable } from "svelte/store";

export const feedbackStore = writable([
    {name:"Palak" , email:"palak@gmail.com", feedback:"Feedback Message"},
    {name:"Kevin" , email:"kevin@gmail.com", feedback:"Feedback Message"},
    {name:"Bharti" , email:"bharti@gmail.com", feedback:"Feedback Message"},
    {name:"Parth" , email:"parth@gmail.com", feedback:"Feedback Message"},
    {name:"Kevin" , email:"kevin@gmail.com", feedback:"Feedback Message"},
    {name:"Bharti" , email:"bharti@gmail.com", feedback:"Feedback Message"},
    {name:"Vishruti" , email:"vishruti@gmail.com", feedback:"Feedback Message"},
    {name:"Mona" , email:"mona@gmail.com", feedback:"Feedback Message"},
    {name:"Nilesh" , email:"nilesh@gmail.com", feedback:"Feedback Message"},
    {name:"Ram" , email:"ram@gmail.com", feedback:"Feedback Message"},
    {name:"Shyam" , email:"shyam@gmail.com", feedback:"Feedback Message"},
    {name:"Janvi" , email:"Janvi@gmail.com", feedback:"Feedback Message"},
    {name:"Hardik" , email:"Hardik@gmail.com", feedback:"Feedback Message"},
    {name:"Zalak" , email:"Zalak@gmail.com", feedback:"Feedback Message"},
    {name:"Jitesh" , email:"Jitesh@gmail.com", feedback:"Feedback Message"},
    {name:"Jayesh" , email:"Jayesh@gmail.com", feedback:"Feedback Message"},
    {name:"Pratik" , email:"Pratik@gmail.com", feedback:"Feedback Message"},
    {name:"Narendra" , email:"Narendra@gmail.com", feedback:"Feedback Message"},
    {name:"Kush" , email:"Kush@gmail.com", feedback:"Feedback Message"},
    {name:"Keval" , email:"Keval@gmail.com", feedback:"Feedback Message"},
    {name:"Ishan" , email:"Ishan@gmail.com", feedback:"Feedback Message"},
    {name:"Vihan" , email:"Vihan@gmail.com", feedback:"Feedback Message"},
    {name:"Ayushi" , email:"Ayushi@gmail.com", feedback:"Feedback Message"},
    {name:"Payal" , email:"payal@gmail.com", feedback:"Feedback Message"},
    {name:"Sooraj" , email:"sooraj@gmail.com", feedback:"Feedback Message"},
    {name:"Aarav" , email:"Aarav@gmail.com", feedback:"Feedback Message"},
    {name:"Chirag" , email:"Chirag@gmail.com", feedback:"Feedback Message"},
    {name:"Darshan" , email:"darshan@gmail.com", feedback:"Feedback Message"}
]);